In [1]:
from tensorflow import keras
import numpy as np

In [2]:
data_set = np.loadtxt('data/ThoraricSurgery3.csv', delimiter=",")
data_set[:3]

array([[ 1.  ,  2.88,  2.16,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,
         3.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 60.  ,  0.  ],
       [ 2.  ,  3.4 ,  1.88,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 51.  ,  0.  ],
       [ 2.  ,  2.76,  2.08,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 59.  ,  0.  ]])

In [3]:
X = data_set[:, :16]
Y = data_set[:, 16]

In [4]:
X[:3]

array([[ 1.  ,  2.88,  2.16,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,
         3.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 60.  ],
       [ 2.  ,  3.4 ,  1.88,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 51.  ],
       [ 2.  ,  2.76,  2.08,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  , 59.  ]])

In [5]:
Y[:3]

array([0., 0., 0.])

In [6]:
model = keras.Sequential()
model.add(keras.Input(shape=(16,)))
model.add(keras.layers.Dense(30, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                510       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
history = model.fit(X, Y, epochs=5, batch_size=16)

Epoch 1/5
30/30 [==============================] - 0s 1ms/step - loss: 19.0489 - accuracy: 0.1489
Epoch 2/5
30/30 [==============================] - 0s 1000us/step - loss: 6.5010 - accuracy: 0.1787
Epoch 3/5
30/30 [==============================] - 0s 1ms/step - loss: 0.6003 - accuracy: 0.7851
Epoch 4/5
30/30 [==============================] - 0s 1ms/step - loss: 0.5024 - accuracy: 0.8511
Epoch 5/5
30/30 [==============================] - 0s 1ms/step - loss: 0.4703 - accuracy: 0.8489
